### ISSUE TITLE
implement cascade delete

### ISSUE THREAD

**Issue by halimpuckjava** [kaiso/relmongo#14]

**Comment by kaiso** [comment]
Hello, Thank you for reporting this enhancement feature
 I will change this to implement cascade delete because I already created an issue for 
cascade persist

**Comment by kaiso** [comment]
delivered in the following versions :
- [v2.1.0](https://github.com/kaiso/relmongo/releases/tag/v2.1.0)
- [v1.2.0](https://github.com/kaiso/relmongo/releases/tag/v1.2.0)
