### ISSUE TITLE
RelMongo improvement

### ISSUE THREAD

**Issue by halimpuckjava** [kaiso/relmongo#29]
hi

i have one issue (A) and one suggestion (B)

A. with last exemple (car & person), when load person document
@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.XXX)
@JoinProperty(name = "cars")
List<Car> cars;

1. XXX = EAGER : person loaded with cars and print in console with success
2. XXX = LAZY : person load (include cars) with success, but when print this person in console, an exception appear like this : 
java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.example.demo.entity.Car

in spring data jpa we can resolve this by add : spring.jpa.hibernate.enable_load_lazy_no_trans=true (application.properties) and all work fine, how about spring data mongodb ???   

B. orphanRemoval implemnation in @OneToMany

**Comment by kaiso** [comment]
Hello,

I couldn't reproduce the issue you described, can you give me the complete example you tested plz?

**Comment by kaiso** [comment]
the 2.2.1 version was release please test and give your feedback, you can close the issue if your tests are concluant.
regarding the orphanRemoval, you can submit a new dedicated issue.
Thank you
