### ISSUE TITLE
add orphanRemoval attribute to @OneToMany and @OneToOne to remove associated document

### ISSUE THREAD

**Issue by halimpuckjava** [kaiso/relmongo#31]
hi

with version 2.2.1, bug fixed, its works fine with fetch = LAZY.

i not see any implemenation of orphanRemoval in this version

**Comment by kaiso** [comment]
The version 2.3.0 of RelMongo which includes this feature was released 
see https://github.com/kaiso/relmongo/releases/tag/v2.3.0
please close this issue

**Comment by halimpuckjava** [comment]
hi

i will try it soon and give you a feedback 

thanks
