### ISSUE TITLE
java.lang.IllegalArgumentException when @Id field is null but type of @Id field is String

### ISSUE THREAD

**Issue by guptaavi** [kaiso/relmongo#32]
I have a child Document that has an @Id field of type String (as opposed to ObjectId). As per the documentation, if the related child document has no id ( does not exist in the database) it needs to be created and automatically linked to the parent document by RelMongo. 
When I try to save the child document, I get a  java.lang.IllegalArgumentException "Can not set java.lang.String field xxx.Person.id to org.bson.types.ObjectId"

In the checkIdentifier method of class io.github.kaiso.relmongo.events.callback.PersistentPropertyConvertingCallback a check is made to see if the Mongo id is null, and if so, a new ObjectId is generated.

```
			if (id == null) {
				objectIdReaderCallback.getIdField().set(obj, ObjectId.get());
			}
```
However, the code above assumes the type of the id field is ObjectId and hence the exception.

**Comment by kaiso** [comment]
Hi,

Thank you for reporting the issue, it will be fixed in the next release of RelMongo. Until that you can use Ids of type ObjectId.

**Comment by kaiso** [comment]
the version 2.3.0 of RelMongo which fixes this issue was released 
see https://github.com/kaiso/relmongo/releases/tag/v2.3.0
please close the issue if your tests are concluding

**Comment by guptaavi** [comment]
Works as expected now. Thanks! Closing issue #32
