### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [kaiso/relmongo#34]
Hello @kaiso 

I wanted to design a new logo for relmongo. I think this looks more modern. I just want to help. I can send you a pr if you want. Also, Please tell me if there is a place you want to customize. I will wait for feedback.

Have a nice day!

![mongo2](https://user-images.githubusercontent.com/36298335/45889554-6f689080-bdc9-11e8-9bdf-4f5e35e8b421.jpg)

**Comment by kaiso** [comment]
Hello @reallinfo Thank you very much for your interest in RelMongo. 
I really like your design, can you propose another with a unique color so that we can choose between your first logo and the second.

Thank you.

**Comment by kaiso** [comment]
due to long time without answer I will close the issue, you can join chat on gitter if you wanna talk about this issue.
