### ISSUE TITLE
RelMongo not working with AbstractConfiguration (MongoDB 4.0 Transactions)

### ISSUE THREAD

**Issue by inblind** [kaiso/relmongo#36]
Hi All,

Issue:
For enabling transactions on MongoDB 4.0 it is required to use AbstractConfiguration. When I add this configuration RelMongo stops working.

Implementation:

public class MongoTransactionConfig extends AbstractMongoConfiguration {

    @Bean
    MongoTransactionManager transactionManager(MongoDbFactory dbFactory) {
        return new MongoTransactionManager(dbFactory);
    }

    @Value("${spring.data.mongodb.host}")
    private String host;

    @Value("${spring.data.mongodb.port}")
    private Integer port;

    @Value("${spring.data.mongodb.database}")
    private String database;

    @Override
    protected String getDatabaseName() {
        return database;
    }

    @Override
    @Bean
    public MongoClient mongoClient() {
    return new MongoClient(host, port);
    }

}

PS: Great dependency, I love how it smooth it is.

Thanks,
Rafael

**Comment by kaiso** [comment]
Hi Rafael,

I did not experiment mongodb transactions yet but I will test it for you and check the problem with RelMongo

**Comment by kaiso** [comment]
Hi, I released a new version [3.0.0](https://github.com/kaiso/relmongo/releases/tag/v3.0.0) which is compatible with transactions and MongoDB 4.0, enjoy ! and do not forget to star the repository.
be free to report any issue and close this issue if your tests are concluding

Thank you,

**Comment by inblind** [comment]
Wow! thanks for that!! awesome job!
