### ISSUE TITLE
Add ManyToMany annotation

### ISSUE THREAD

**Issue by mojo2012** [kaiso/relmongo#39]
It would be nice to have a `ManyToMany` annotation that works similar to the JPA annotation.

**Comment by kaiso** [comment]
I agree, it will study the feasability of it.

**Comment by kaiso** [comment]
Hello, I've tried some implementation but currently the performance of lookups are very poor in addition MongoDB has no tools to make joins so I think that delivering such feature will not be suitable at the moment. So you have to implement it your way with queries. May be in the feature we will have other tools to do that.

**Comment by mojo2012** [comment]
Damn :-\ Thanks for your efforts anyways!
