### ISSUE TITLE
Failed in bidirectional mapping when one of the audit fields gets updated.

### ISSUE THREAD

**Issue by anz000** [kaiso/relmongo#41]
I have manyToOne and oneToMany relationship like
```
class A {
...
@OneToMany
List<B> b;
@LastModifiedDate
private LocalDateTime lastModifiedDate;
}
```

```
class B {
...
@ManyToOne
A a;
}
```

This fails because the auditing field lastModifiedDate, gets updated (I think) and the save method fails. removing the auditing field works fine.
`
org.springframework.data.mapping.MappingException: Cannot lookup property @io.github.kaiso.relmongo.annotation.ManyToOne(mappedBy=gists, fetch=LAZY)private com.timecloud.source.entity.pojo.ClassA com.timecloud.gist.entity.ClassB.source on null intermediate! Original path was: source.lastModifiedDate on com.timecloud.gist.entity.ClassB.`

**Comment by kaiso** [comment]
when you implement a bidirectional mapping you have to use the ˋmappedBy` attribute in one side of the mapping. Have you done so ?

**Comment by kaiso** [comment]
Sorry I will close this issue, I'm able to use auditing annotations without any problem, please take a look at relmongo tests to see an example on that.
