### ISSUE TITLE
Cascade Type REMOVE not deleting child attributes on Query.

### ISSUE THREAD

**Issue by anz000** [kaiso/relmongo#47]
I have entities similar to this.

```
public class Parent {
    @OneToMany(fetch= FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    @JoinProperty(name="childrens")
    private List<Child> childrens;

}
```

```
public class Child {
   @ManyToOne(mappedBy = "childrens", fetch= FetchType.EAGER)
    private Parent parent;
}
```

I've implemented something like
```
public class ParentRepository extends MongoRepository<Parent, ObjectId> {
    @DeleteQuery( value = "{'property1' : ?0, 'property2' : ?1 }")
    void deleteParentByProperties(String property1, String property2);
}
```

when I do `parentRepository.deleteParentByProperties("param1", "param2");`
-> It deleted the parent but not the child (Note: this is a custom method implemented with a Query - but still native?)

when I do `parentRepository.delete(parent);`
-> It deletes the child as well (works as expected). (Note : This is a native method)

Instead of individual parent, I wanted to delete all parent that match a certain condition and avoid doing a fetch query.

**Comment by kaiso** [comment]
Hello, unfortunately, like in JPA, A delete query operation only applies to entities of the specified class and its subclasses. It does not cascade to related entities.
So you can either call find with criteria and loop on the results by calling repository.delete(entity). in most of cases it is the recommanded solution. Or creating a custom implementation where you remove by a criteria from both collections.

**Comment by anz000** [comment]
Thanks. I've decided to just fetch the `list of parents` and call `parentRepository.deleteAll(parentList)`. This deletes the associated children as well.

I've read on the documentation and still am confused about the `mappings` I have (`mappedBy`) and `orphanRemoval`. Based on the code I provided earlier, is there a scenario where a parent might get deleted when a child gets deleted? Quick mock tests  didn't seem to suggest so, but I'm not entirely confident. I'd love to know if I had `mappedBy` on the other side, how would the relationship change. Thanks.

**Comment by kaiso** [comment]
the `orphanRemoval` and cascading only concerns children so the parent won't be deleted.
regarding the second question, the `mappedBy` attribute allows simply to fetch the other direction of the mapping (aka the owner of the relation).

**Comment by anz000** [comment]
The owner of the relation and parent of the relation is the same thing? This is where my confusion lies. Does putting `mappedBy` in one class make it parent or the child of the relation? Is my class structure (one that I posted in the first comment) good enough to assume that `Parent`class is the `owner` of the relation? Sorry, this has gone beyond the scope of the issue, but any insight would be highly appreciated. Thanks.

**Comment by kaiso** [comment]
exaclty like your example the Parent class is the owner. the mappedBy attribute does not make the owner of the relation and to go further the owner is the document that stores references to the other collection in MongoDB, in your case the references will be stored in the parent collection
