### ISSUE TITLE
Add multi level relations loading support

### ISSUE THREAD

**Issue by sverin** [kaiso/relmongo#52]
I having an issue when I fetching objects that have relationship in more than one level. I have 3 different classes that reference to each other by a one-to-one relationship, as shown below.

```
@Document(collection = "products")
@TypeAlias(value = "product")
public class Product {
  
  @Id
  private String id;

  private String name;

  @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
  @JoinProperty(name = "variations")
  private List<ProductVariation> variations;

}
```

```
@Document(collection = "variations")
@TypeAlias(value = "variation")
public class ProductVariation {

  @Id
  private String variationId;

  private String name;

  @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
  @JoinProperty(name = "options")
  private List<Option> options;

}
```

```
@Document(collection = "options")
@TypeAlias(value = "option")
public class Option {

  @Id
  private String optionId;

  private String text;

}
```

Through a spring-controller and spring repository I can add some data to MongoDB database. But then my issue starts. As you can see in the repsonse below the option does not have any text value when I use a `ProductRepository` to fetch the data. I have checked the MongoDB database and the data has been saved correctly.

```
[
  {
    "id": "5ef4998e0a994e434d6cce86",
    "name": "My Product Name",
    "variations": [
      {
        "id": "5ef4998e0a994e434d6cce84",
        "name": "My Product Variation Name",
        "options": [
          {
            "id": "5ef4998e0a994e434d6cce88",
            "text": null
          }
        ]
      }
    ]
  }
]
```
However, if I use a `ProductVariationRepository` and do the fetch one level down, it works perfectly.
```
[
  {
    "id": "5ef4998e0a994e434d6cce84",
    "name": "My Product Variation Name",
    "options": [
      {
        "id": "5ef4998e0a994e434d6cce88",
        "text": "My options value"
      }
    ]
  }
]
```
Is this a bug? Can't you have multi level relationship? Or have I missed something in my configuration ?

**Comment by kaiso** [comment]
Hello Sevrin,

Thank you for using RelMongo, currently it does not support multi-level relationships loading it is a limitation you can submit an issue of type enhancement and I will see if it is possible to do that. 
Do not forget to star the repository ;) 

Regards,
kaiso.

**Comment by sverin** [comment]
Thank you for your quick response. Its a great library, and this would make it even better.

**Comment by kaiso** [comment]
Hello @sverin I've published a release candidate version **3.4.0-RC1** to address the multi level loading feature.
can your test and give me your feedback please?
Thank you

**Comment by sverin** [comment]
I have tried it today and it works perfectly. It all works as I expected now. I will try it out some more until friday and if I have some issues I'll let you know. Thanks for your quick response. This framework just become even better.

**Comment by sverin** [comment]
I have tried it now for a couple of days and it works fine. If you feel comfortable with the code you can close the issue and make a final release.

**Comment by kaiso** [comment]
Thank you @sverin I will release the version then.

**Comment by loehnertz** [comment]
@sverin
I have _almost exactly_ the same setup as you posted in your first comment above.
The only differences are that I have `@OneToOne` relations and that I am using Kotlin instead of Java (I don't think this causes a problem in this particular case, but it could potentially).
Apart from that, it's the same. I am running on v3.4.1. I also have three collections with the same nesting structure.
However, I cannot get it to work. For me, arbitrary, non-relational fields are `null` when loaded out of MongoDB again. The persisting works just fine. With only one level of relation, it also works perfectly.

When you wrote:
> I have tried it today and it works perfectly. It all works as I expected now.
Did you refer to the same setup as you posted initially or did you change some details afterward in your running solution?
