### ISSUE TITLE
How to update and delete child document in oneToMany relationship

### ISSUE THREAD

**Issue by PraveenBiradar** [kaiso/relmongo#57]
How to update and delete child document using parentId and childId in oneToMany relationship

Update:		@PutMapping("/posts/{postId}/comments/{commentId}")
			public Comment updateComment(@PathVariable (value = "postId") Long postId,@PathVariable (value = 
                                                          "commentId"),Long commentId,@RequestBody Comment commentRequest) {
				// Update Logic -  query
			}

Delete:  	@DeleteMapping("/posts/{postId}/comments/{commentId}")

**Comment by kaiso** [comment]
@PraveenBiradar In order to implement the the update and logic you have to look at spring data mongodb docs.
and then you implement the cascading in parent/child relationship as explained in https://github.com/kaiso/relmongo/wiki/RelMongo-Cascading
