### ISSUE TITLE
Support for _id of type Long

### ISSUE THREAD

**Issue by i-telligence-af** [kaiso/relmongo#59]
According to the mapping chapter of mongodb 1.3.3.RELEASE, the _id field can be of any type other than arrays.

https://docs.spring.io/spring-data/mongodb/docs/1.3.3.RELEASE/reference/html/mapping-chapter.html

_7.1.1 How the '_id' field is handled in the mapping layer
MongoDB requires that you have an '_id' field for all documents. If you don't provide one the driver will assign a ObjectId with a generated value. The "id" field can be of any type the, other than arrays, so long as it is unique.

I've forked 3.4.0-RC1 and adapted [io.github.kaiso.relmongo.util.ObjectIdReaderCallback](https://github.com/i-telligence-af/relmongo/blob/long_id/src/main/java/io/github/kaiso/relmongo/util/ObjectIdReaderCallback.java) to also support Long.

Do you think that is sensible? I guess other types should be supported as well?

I've also had to adapt the mapIdentifier method in [io.github.kaiso.relmongo.mongo.DocumentUtils](https://github.com/i-telligence-af/relmongo/blob/long_id/src/main/java/io/github/kaiso/relmongo/mongo/DocumentUtils.java) respectively.

I've create the following pull request: https://github.com/kaiso/relmongo/pull/58

If you are happy with this, I will try to adapt it accept any type other than arrays.

Many thanks and happy weekend!

**Comment by kaiso** [comment]
Hello @i-telligence-af thank you for your interest on RelMongo, I've released a new version (**3.4.1-RC1**) can you test and give me your feedback please?

**Comment by i-telligence-af** [comment]
Hi @kaiso , thanks for the quick reply!

Yes, that seems to work perfectly! Shall I close this issue now, or do you want to close it when the changes are in github?

**Comment by kaiso** [comment]
Hello @i-telligence-af , glad that it fixes your problem, I will close the issue and also your pull request since I fixed other aspects on other commits. feel free to submit issues if needed.
