### ISSUE TITLE
Support for annotations within nested objects

### ISSUE THREAD

**Issue by i-telligence-af** [kaiso/relmongo#60]
I have a scenario where an object has an embedded object (field) which itself is persisted as part of the outer @Document but annotated fields within the embedded object should be scanned for @OneToOne and @OneToMany annotations.

Example:

```
ArticleDTO {

  @Id
  private Long id;

  @OneToOne(...)
  @JoinProperty(...)
  private OtherDTO other;

  private MetaDTO meta;

}

MetaDTO {

  @Id
  private Long id;

  @OneToOne(...)
  @JoinProperty(...)
  private FooDTO foo;

}
```

Currently, the annotations on the FooDTO field in MetaDTO would never be read.

How about a @Nested annotation, which would then perform the same functionality on the MetaDTO field?

**Comment by kaiso** [comment]
Hello @i-telligence-af thank you for your interest in RelMongo, currently this problem can be adressed by minimal change in the entity by putting the foo property outside. So I do not see and enhancement in that, I will close this issue and may be reconsider the use case if many people have this need. 

Thank you and do not forget to star RelMongo ;)

**Comment by i-telligence-af** [comment]
Hi @kaiso unfortunately modifying the structure of my entities is not an option currently (I don't have control), so I will keep using my fork for now. I'll try to keep it inline with your updates, so that if you ever want to include this enhancement it should be easy.

Thanks for the great work.... starred ;)
