### ISSUE TITLE
Exception - unable to set mappedBy child object 

### ISSUE THREAD

**Issue by munish-usit** [kaiso/relmongo#66]
I am using below structure

class ProfileEntity{
.......
@OneToMany(fetch=FetchType.EAGER, cascade=CascadeType.PERSIST)
	@JoinProperty(name="emailNotificationsId")
	private List<EmailNotificationsEntity> emailNotifications;
}

public class EmailNotificationsEntity {

	@Id
	private Integer emailNotificationsId;
	@Field(name="email_notifications_name")
	private String name;
	
	@ManyToOne(mappedBy = "emailNotifications")
	private List<ProfileEntity> profiles;
}

For this structure i am getting below error while fetching ProfileEntity data

io.github.kaiso.relmongo.exception.RelMongoProcessingException: unable to set mappedBy child object Can not set java.util.List field com.test.core.profile.entity.EmailNotificationsEntity.profiles to com.test.core.profile.entity.ProfileEntity

**Comment by kaiso** [comment]
Hello @munish-usit thank you for using RelMongo, your issue is that `@ManyToOne` can only be used on an attribute of type object and not collection so in your case you should have :
`@ManyToOne(mappedBy = "emailNotifications")
private ProfileEntity profile; `

**Comment by munish-usit** [comment]
Hello @kaiso ,
Thanks for your solution. Your solution has solved the run time error, but unfortunately, in my use case I have to use List<ProfileEntity> profiles because its a many to many relationship.
One profile can have many email notifications.
One email notification can be subscribed by many profile.

Do you have any plan to support List in many to many relationship ?

Thanks,
Munish

**Comment by kaiso** [comment]
Hello @munish-usit Unfortunately I have no plan for that for now, I have studied the feature and the outcome was that it is very complex.
