### ISSUE TITLE
PersistentPropertyPostLoadingCallback.close() never called.... memory leak?

### ISSUE THREAD

**Issue by i-telligence-af** [kaiso/relmongo#67]
Hi Kaiso!

I'm getting OutOfMemory errors in my application and after analysing the heap dump, it looks like it may be due to the close() method of PersistentPropertyPostLoadingCallback never being called. 

I do have to mention though, that I am running on a fork... which has a feature which you decided not to include (https://github.com/kaiso/relmongo/issues/60). So maybe it will only ever be me having this problem, as I instantiate an instance of PersistentPropertyPostLoadingCallback within PersistentPropertyPostLoadingCallback itself.

Thought I would mention it just in case though.

Many thanks again for your great work, keep it up!

**Comment by kaiso** [comment]
Hello @i-telligence-af thank you for reporting the problem. I've removed this experimental caching mechanism and released a new version **v3.4.2**, can you check and close this issue please?

**Comment by mistermusk** [comment]
@kaiso thanx for the reply!

**Comment by i-telligence-af** [comment]
Hi Kaiso,

sorry for the late reply. I've now merged your master with my fork. And will deploy to our frontends to test.

**Comment by i-telligence-af** [comment]
Hey Kaiso,

looks all good, many thanks!
