### ISSUE TITLE
JoinTable analogue

### ISSUE THREAD

**Issue by mistermusk** [kaiso/relmongo#70]
Hello again @kaiso!
-
Could you kindly tell me if it is possible with relmongo: 

Example with mysql:
`
@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name = "users_roles",
               joinColumns = @JoinColumn(name = "user_id"),
               inverseJoinColumns = @JoinColumn(name = "role_id"))
`

Thank you in advance.
P.S. Sorry for writing here - haven't found your contact details. I will close issue)

**Comment by kaiso** [comment]
Hello @mistermusk Thank you for using RelMongo, unfortunately there is no `@ManyToMany` annotation currently.

**Comment by mistermusk** [comment]
@kaiso thanx for the reply!
