### ISSUE TITLE
Enable multiple mongoTemplate support

### ISSUE THREAD

**Issue by kaiso** [kaiso/relmongo#72]
* Change the @EnableRelMongo annotation to have a new attribute mongoTemplateRef.
* Change the RelMongo logic to be able to target a specifig mongoTemplate.

**Comment by kushalgupta36** [comment]
Hey
I guess I am getting this issue right now. I am using multiple mongo dbs in my springboot application and for that I am using custom mongo template names. So are there any workarounds for now?

**Comment by kaiso** [comment]
Hello @kushalgupta36 can you use the version `3.5.0-RC4` which allows to specify the mongo template to target ?
use the following code :
```java
@EnableRelMongo(mongoTemplateRef = "mongoTemplate")
```

**Comment by kushalgupta36** [comment]
Hey @kaiso, i used the version 3.5.0-RC4, it worked flawlessly. Thanks!
