### ISSUE TITLE
Order of List<>   changes when using  @OneToMany relation

### ISSUE THREAD

**Issue by andy-mueller** [kaiso/relmongo#77]
Hi,

we are using a one to many relation  from a PersistedCase to a PersistedPerson:

`@OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.NONE)
@JoinProperty(name = "offers")
 private List<PersistedOffer> offers = new ArrayList<>();`

Then we add Persons in a specific order and save it. In 20-50% of the cases the order of the Persons lists order has changed  when I look into the DB.

Best
Andreas

**Comment by kaiso** [comment]
Hello @andy-mueller yes there is no guarantee on the order of the elements in the array, you should specify order through a comparator on java side.
