### ISSUE TITLE
OneToMany relation is saved as sub documents and not in a separate collection after update to spring boot 2.7.5

### ISSUE THREAD

**Issue by andy-mueller** [kaiso/relmongo#97]
Hi,
after upgrading from spring boot 2.5.5 to 2.7.5, relmongo saves the related objects as subdocuments:

```
class Case{
    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.NONE)
    @JoinProperty(name = "persons")
    private List<Person> persons = new ArrayList<>();
}

class Person{
   @Id
    String _id;
   String name;
   String email;
}
```

Saving the Case, results in this DB entry:

```
{
    "persons" : [
        {"_id": "XXX", "name"="Paul", "emai"l; "paul@..."},...
    ]
}
```
Loading does not touch the "persons" collection as well!

This behavior started with the upgrade to ne new Spring boot version.

**Comment by andy-mueller** [comment]
While trying to fix it, I could narrow the versions a little bit down. In June we went from 3.4.0 to 3.4.0, because the older Version has a memory leak in a cache and was causing out of memory crashes. At this time we were using spring boot 2.5.5. Before that it worked as expected. 
It also looks like the OneToOne relations are working as adevertized

**Comment by kaiso** [comment]
Hello sorry for the late response, I will update the comptatibility with spring boot 2.7 soon

**Comment by kaiso** [comment]
I have updated RelMongo to support :
spring 6
spring-data 4
spring-boot 3

the release version is [4.0.0-RC1](https://repo1.maven.org/maven2/io/github/kaiso/relmongo/relmongo/4.0.0-RC1/)
Feel free if there are any problems
